### ISSUE TITLE
[BUG] Rich doesn't work with Python <3.6.3, so its mimimum version should be bumped to 3.6.3

### ISSUE THREAD

**Issue by DrBenton** [Textualize/rich#2162]

**Comment by henryiii** [comment]
I’m curious on this one, so you know why? 3.6.3 was the fist version to use MSVC 2017, but otherwise not sure why 3.6.3 might be needed. Do older versions work on 3.6.3? Also scary to thing someone would still have 3.6.3 around to discover this. :)

**Comment by DrBenton** [comment]
Hi!

It seems related to [this change](https://github.com/Textualize/rich/pull/2091/files) that was merged recently on the LRUCache class: with Python 3.6.1 and 3.6.2 the fact that this class now inherits from `OrderedDict[CacheKey, CacheValue]`  triggers a rather cryptic (to me, at least :sweat_smile: ) error in the `typing_extensions` package: 
> AttributeError: type object 'LRUCache' has no attribute '_gorg'

The test output with Python 3.6.2:
```
____________________________________________________________________ ERROR collecting tests/test_align.py ____________________________________________________________________
tests/test_align.py:5: in <module>
    from rich.console import Console
rich/console.py:47: in <module>
    from ._log_render import FormatTimeCallable, LogRender
rich/_log_render.py:4: in <module>
    from .text import Text, TextType
rich/text.py:8: in <module>
    from rich.emoji import EmojiVariant
rich/emoji.py:6: in <module>
    from .jupyter import JupyterMixin
rich/jupyter.py:4: in <module>
    from .segment import Segment
rich/segment.py:9: in <module>
    from .cells import (_is_single_cell_widths, cell_len, get_character_cell_size,
rich/cells.py:12: in <module>
    def cell_len(text: str, _cache: Dict[str, int] = LRUCache(1024 * 4)) -> int:
.venv-3.6.2/lib/python3.6/site-packages/typing_extensions.py:492: in __new__
    if cls._gorg is OrderedDict:
E   AttributeError: type object 'LRUCache' has no attribute '_gorg'
========================================================================== short test summary info ===========================================================================
ERROR tests/test_align.py - AttributeError: type object 'LRUCache' has no attribute '_gorg'
